// Generated by CharGPT

// Root object
export interface IAnidbAnimeData {
  anime: Anime;
  error?: {
    code: string;
    message: string;
  };
}

// Anime element
interface Anime {
  id: string; // Attribute
  restricted: string; // Attribute
  type: string;
  episodecount: string;
  startdate: string;
  enddate: string;
  titles: Titles;
  relatedanime: RelatedAnime;
  recommendations: Recommendations;
  url: string;
  creators: Creators;
  description: string;
  ratings: Ratings;
  picture: string;
  resources: Resources;
  tags: Tags;
  characters: Characters;
  episodes: Episodes;
}

// Titles
interface Titles {
  title: Title[]; // Array of Title
}

interface Title {
  "xml:lang": string; // Attribute
  type: string; // Attribute
  "#text": string;
}

// Related Anime
interface RelatedAnime {
  anime: RelatedAnimeEntry;
}

interface RelatedAnimeEntry {
  id: string; // Attribute
  type: string; // Attribute
  "#text": string;
}

// Recommendations
interface Recommendations {
  total: string; // Attribute
  recommendation: Recommendation;
}

interface Recommendation {
  type: string; // Attribute
  uid: string; // Attribute
  "#text": string;
}

// Creators
interface Creators {
  name: Creator[]; // Array of Creator
}

interface Creator {
  id: string; // Attribute
  type: string; // Attribute
  "#text": string;
}

// Ratings
interface Ratings {
  permanent: Rating;
  temporary: Rating;
}

interface Rating {
  count: string; // Attribute
  "#text": string;
}

// Resources
interface Resources {
  resource: Resource[]; // Array of Resource
}

interface Resource {
  type: string; // Attribute
  externalentity: ExternalEntity;
}

interface ExternalEntity {
  identifier?: string;
  url?: string;
}

// Tags
interface Tags {
  tag: Tag[]; // Array of Tag
}

interface Tag {
  id: string; // Attribute
  parentid?: string; // Attribute
  infobox?: string; // Attribute
  weight: string; // Attribute
  localspoiler: string; // Attribute
  globalspoiler: string; // Attribute
  verified: string; // Attribute
  update: string; // Attribute
  name: string;
  description?: string;
  picurl?: string;
}

// Characters
interface Characters {
  character: Character[]; // Array of Character
}

interface Character {
  id: string; // Attribute
  type: string; // Attribute
  update: string; // Attribute
  rating?: Rating;
  name: string;
  gender: string;
  charactertype: CharacterType;
  description?: string;
  picture?: string;
  seiyuu?: Seiyuu | Seiyuu[]; // Can be single or array
}

interface CharacterType {
  id: string; // Attribute
  "#text": string;
}

interface Seiyuu {
  id: string; // Attribute
  picture: string; // Attribute
  "#text": string;
}

// Episodes
interface Episodes {
  episode: Episode[] | Episode; // Array of Episode
}

interface Episode {
  id: number; // Attribute
  update: string; // Attribute
  epno: Epno;
  length: string;
  airdate: string;
  rating?: Rating;
  title?: Title | Title[]; // Can be single or array
}

interface Epno {
  type: number; // Attribute
  "#text": number;
}
